- hosts: localhost
  remote_user: root
  become: true

  vars:

    - ICTF_TI_SERVER_URL: "https://api.seba.net"
    - ICTF_DB_API_SECRET: "{{ lookup('file', '/opt/ictf/secrets/database-api/secret') }}"
    - ICTF_TI_SECRET_KEY: "{{ lookup('password','/opt/ictf/secrets/ti_secret length=25') }}"

    - SENDGRID_API_KEY: ""
    - ICTF_EMAIL_SENDER: ""
    - ICTF_TI_SERVER_DOMAIN: "api.ictf2017.net"

    # to obtain a SSL cert with letsencrypt see https://certbot.eff.org/#ubuntutrusty-nginx
    - SSL_CERTIFICATE_PATH: "/etc/letsencrypt/live/api.ictf2017.net/fullchain.pem"
    - SSL_CERTIFICATE_KEY_PATH: "/etc/letsencrypt/live/api.ictf2017.net/privkey.pem"
    - ENABLE_SSL: "0"

    # Team interface config
    - REGISTRATION_OPEN: "False"
    - GAME_STARTED: "False"
    - SUBMISSION_OPEN: "False"
    
  tasks:
    # - include_role:
    #     name: common
    #   vars:
    #     swapfile_size: "2G"

    # - name: teaminterface - write config.py
    #   copy:
    #     src="/opt/ictf/teaminterface/config.py.example"
    #     dest="/opt/ictf/teaminterface/config.py"
    #     mode="0666"
    #   notify:
    #     - restart ictf-teaminterface

    # sysctl
    # - name: sysctl - performance tuning
    #   copy:
    #     src=/opt/ictf/teaminterface/support/sysctl.conf
    #     dest=/etc/sysctl.d/99-ictf-teaminterface.conf
    #     owner=root group=root mode="u=rw,g=r,o=r"

    # - name: sysctl - reload
    #   command: sysctl -p /etc/sysctl.d/99-ictf-teaminterface.conf
    #   tags: [skip_ansible_lint]

    # - name: virtualenv - install setuptools
    #   pip:
    #     name: setuptools==44.0.0
    #     virtualenv: /opt/ictf/venv/teaminterface
    #   become: true

    # - name: virtualenv - install requirements
    #   pip:
    #     requirements=/opt/ictf/teaminterface/requirements.txt
    #     virtualenv=/opt/ictf/venv/teaminterface

    # ictf-teaminterface configuration
    # - include_role:
    #     name: register_service_daemon
    #   vars:
    #     service_name: ictf-teaminterface
    #     description: "iCTF Team Interface API service"
    #     command:  "/opt/ictf/venv/teaminterface/bin/uwsgi -s /tmp/ictf-api.sock --chmod-socket --virtualenv=/opt/ictf/venv/teaminterface --logto /tmp/uwsgi.log --module team_interface --callable app --enable-threads -z 6000 --master --listen 65535 --processes 10 --max-requests 655350 --die-on-term"
    #     working_directory: "/opt/ictf/teaminterface"

    # setup nginx
    - name: nginx - allow worker processes, 4 per core
      lineinfile:
        dest=/etc/nginx/nginx.conf
        regexp="(worker_processes).*$"
        line="worker_processes {{ 4 * ansible_processor_cores }};"

    - name: nginx - allow more open files
      lineinfile:
        dest=/etc/nginx/nginx.conf
        regexp="^worker_rlimit_nofile"
        line="worker_rlimit_nofile 512000;"
        insertafter="(worker_processes).*"

    - name: nginx - set worker connections to 4096
      lineinfile:
        dest=/etc/nginx/nginx.conf
        regexp="(worker_connections).*$"
        line="\tworker_connections 4096;"

    - name: nginx - disable default configuration
      file:
        path=/etc/nginx/sites-enabled/default
        state=absent recurse=no

    - name: nginx - add ictf-teaminterface
      template:
        src=/opt/ictf/teaminterface/support/nginx.conf
        dest=/etc/nginx/sites-available/ictf-teaminterface.conf
        owner=root group=root mode="u=rw,g=r,o=r"
      # notify:
      #   - reload nginx

    - name: nginx - enable ictf-teaminterface
      file:
        src=/etc/nginx/sites-available/ictf-teaminterface.conf
        dest=/etc/nginx/sites-enabled/ictf-teaminterface.conf
        owner=root group=root
        state=link
      # notify:
      #   - reload nginx

    # - include_role:
    #     name: common_server
    #   vars:
    #     server_hostname: TeamInterface

    # - include_role:
    #     name: deploy_prometheus_node_exporter

    # - name: setting hostname
    #   hostname:
    #     name: "teaminterface"

    # - name: Add mappings to /etc/hosts
    #   blockinfile:
    #     dest: /etc/hosts
    #     block: |
    #       {{ item.ip }} {{ item.name }}
    #     marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    #   with_items:
    #     - { name: "teaminterface", ip: 127.0.0.1 }

    - name: teaminterface - write config.py
      template:
        src="/opt/ictf/teaminterface/config.py.example"
        dest="/opt/ictf/teaminterface/config.py"
        mode="0666"
      # notify:
      #   - restart ictf-teaminterface
      #   - reload nginx

    - name: logstash - config
      copy:
        src=./files/logstash.conf
        dest=/etc/logstash/conf.d/syslog.conf
        owner=root group=root mode="u=rw,g=r,o=r"
